### PR TITLE
Added framework project for Carthage support

### PR DESCRIPTION
**Pull request by alexcurylo**
Also reworked example to use framework, and edited README with instructions and badges.

### CODE REVIEW

**Comment by sascha** [comment]
Cool, thanks!

**Comment by alexcurylo** [comment]
You're welcome! One more thing -- there needs to be a new tag available for Carthage to check out automatically. At the moment it'll pull 1.0.3 which won't work, so it'll require a commit hash until that's done.

**Comment by sascha** [comment]
Just created 1.0.4 (and also updated the podspec to 1.0.4 to avoid confusion).

**Comment by alexcurylo** [comment]
Great, thanks!

**Pull request merged**
