### PR TITLE
Replace percentVisible with fractionVisible

### PR DESCRIPTION
**Pull request by AndriyGo**
Throughout the code 'percentVisible' is used to indicate the fraction
visible. The name is ambiguous as it may suggest that the value should
be from 0 to 100, whereas in fact it goes from 0 to 1 (maybe a bit more
with overshoot).

I therefore propose to rename percentVisible into fractionVisible to
make it more clear what this variable is for.

This commit also fixes issues with state restoration of the open side (the state actually gets restored)

### CODE REVIEW

**Comment by sascha** [comment]
I do agree with your reasoning behind the name change, but this would require a major version update. Maybe we should hold this off until Swift 4 is released and we probably have to release a new major version anyway. What are your thoughts?

**Comment by AndriyGo** [comment]
Thanks for getting back.

Regarding the name - we might wait until Swift 4. However, this PR also addresses the issue with state restoration and it is a big one. Basically, there is currently a bug, even in KitchenSink which creates super weird behaviour if the app attempts to restore state to the open drawer.

To repeat it:

1) Open the app and open any drawer.
2) Press home button and stop the execution from Xcode
3) Open the app again. Firstly, the drawer is not open. Secondly, when you open it you see a black screen. This is quite a serious bug which should be fixed. Commit 561ea11 fixes it.

Would you like me to make a PR with only this commit?

**Comment by AndriyGo** [comment]
Actually, 561ea11 is such a simple fix that you can probably copy it and commit it yourself to the master branch. If you do, please do not forget to tag the release as I really need this fix in one of my projects 👍

**Comment by sascha** [comment]
Alright, I've pushed 3.2.1 with the state restoration bugfix and will leave this PR open until there are a few more changes that require a major version update :) Thanks!

**Comment by AndriyGo** [comment]
Great, thanks!

**Pull request closed without merging**
