### PR TITLE
Migrate to Swift 3 & Xcode 8

### PR DESCRIPTION
**Pull request by Dschee**
I ran the Xcode 8 automatic migration from Swift 2 to Swift 3 and updated optimization level as recommended by Xcode. Should now work with Xcode 8.

Anybody interested in trying this out now (in case it doesn't get merged very soon) simply integrate [my fork](https://github.com/Dschee/DrawerController) e.g. via Carthage by using the following:

```
github "Dschee/DrawerController"
```

### CODE REVIEW

**Comment by tinder-sgong** [comment]
Looks like this is not maintained anymore... my PR (https://github.com/sascha/DrawerController/pull/53) in May has been ignored as well... Should I put the PR to your fork and use that from now on? ;)

**Comment by tinder-sgong** [comment]
cc @sascha to see if still interested in maintaining the repo, and thanks for the great work!

**Comment by Dschee** [comment]
Sure, if there's no other active maintainer you can send the PR to my fork, too. I won't have time to habe a look this week though since I'm on vacation without my dev machine. ;)

**Comment by hyouuu** [comment]
Oops used wrong account - deleting the prev comments and reposted here:
Looks like this is not maintained anymore... my PR (#53) in May has been ignored as well... Should I put the PR to your fork and use that from now on? ;)
cc @sascha to see if still interested in maintaining the repo, and thanks for the great work!

**Comment by sascha** [comment]
@Dschee I've been a little busy lately, sorry about that. I've merged your PR into https://github.com/sascha/DrawerController/tree/swift-3.0 which I will try to keep up to date. I will merge it with master as soon as Swift 3.0 is final.

**Pull request closed without merging**
